name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8
      run: flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Validate JSON files
      run: |
        for f in data/*.json; do
          echo "Validating $f"
          python -m json.tool < "$f" > /dev/null || (echo "❌ Invalid JSON: $f" && exit 1)
        done

    - name: Check HTML structure
      run: |
        grep -q "<!DOCTYPE html>" app/index.html || (echo "Missing DOCTYPE" && exit 1)
        grep -q "<title>" app/index.html || (echo "Missing <title>" tag && exit 1)
